import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import useFetchData from "@/hooks/useFetchData";
import { FaGithub, FaHtml5 } from "react-icons/fa6";
import { TbBrandNextjs } from "react-icons/tb";
import { FiDatabase } from "react-icons/fi";
import { AiOutlineDeploymentUnit } from "react-icons/ai";

export default function Home() {
  const [currentPage, setCurrentPage] = useState(1);
  const [perPage] = useState(5); //number of blogs per page

  const { alldata, loading } = useFetchData("api/getblog");

  //function to handle pagination
  const paginate = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  // filter publish blogs
  const publishedblogs = alldata.filter((blog) => blog.status === "publish");

  const indexOfLastBlog = currentPage * perPage;
  const indexOfFirstBlog = indexOfLastBlog - perPage;
  const currentBlogs = publishedblogs.slice(indexOfFirstBlog, indexOfLastBlog);

  const pageNumbers = [];
  for (let i = 1; i <= Math.ceil(publishedblogs.length / perPage); i++) {
    pageNumbers.push(i);
  }

  function extractFirstImageUrl(markdownContent) {
    //Check if the markdown content has an image
    if (!markdownContent || typeof markdownContent !== "string") {
      return null;
    }

    //reguler expression to find the first image in the markdown  ![alt text](image url)
    const regex = /!\[.*\]\((.*)\)/;
    const match = markdownContent.match(regex);
    return match ? match[1] : null;
  }

  return (
    <>
      <Head>
        <title>Front End Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="header_data_section">
        <div className="container flex flex-sb w-100">
          <div className="leftheader_info">
            <h1>
              Hi, I'm <span>Abraham Ortega</span> <br />
              Fullstack Developer
            </h1>
            <h3>Lorem ipsum dolor sit amet.</h3>
            <div className="flex-gap-2">
              <Link href="/contact">
                <button>Contac Me</button>
              </Link>
              <Link href="/about">
                <button>About Me</button>
              </Link>
            </div>
          </div>
          <div className="rightheader_img">
            <img
              style={{ width: "400px" }}
              src="/img/profile.png"
              alt="coder"
            />
          </div>
        </div>
      </section>

      <section className="main_blog_section">
        <div className="container flex flex-sb flex-left flex-warp">
          <div className="leftblog_sec">
            <h2>Recently Published</h2>
            <div className="blogs_sec">
              {loading ? (
                <div className="wh_100 flex flex-center mt-2 pb-5">
                  <div className="loader"></div>
                </div>
              ) : (
                <>
                  {currentBlogs.map((blog) => {
                    {
                      console.log(blog);
                    }
                    //in the markdown content first image show here
                    const firstImage = extractFirstImageUrl(blog.description);
                    return (
                      <div className="blog" key={blog._id}>
                        <div className="blogimg">
                          {/* if not img in markdown show no img*/}
                          <Link href={`/blog/${blog.slug}`}>
                            <img
                              src={firstImage || "/img/noImg.jpg"}
                              alt={blog.title}
                            />
                          </Link>
                        </div>
                        <div className="bloginfo">
                          <Link href={`/tag/${blog.tags[0]}`}>
                            <div className="blogtag">{blog.tags[0]}</div>
                          </Link>
                          <Link href={`/blog/${blog.slug}`}>
                            <h3>{blog.title}</h3>
                          </Link>
                          <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing
                            elit. Soluta ut reiciendis enim saepe mollitia nobis
                            maxime nostrum? Nesciunt, dignissimos qui.
                          </p>
                          <div className="blogauthor flex gap-1">
                            <div className="blogaimg">
                              <img src="/img/profile.png" alt="author" />
                            </div>
                            <div className="flex flex-col flex-left gap-5">
                              <h4>Abraham Ortega</h4>
                              <span>
                                {new Date(blog.createdAt).toLocaleDateString(
                                  "en-US",
                                  {
                                    month: "long",
                                    day: "numeric",
                                    year: "numeric",
                                  }
                                )}
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </>
              )}
            </div>
            <div className="blogpagination">
              <button
                onClick={() => paginate(currentPage - 1)}
                disabled={currentPage === 1}
              >
                Previous
              </button>
              {pageNumbers
                .slice(
                  Math.max(currentPage - 3, 0),
                  Math.min(currentPage + 2, pageNumbers.length)
                )
                .map((number) => (
                  <button
                    key={number}
                    onClick={() => paginate(number)}
                    className={currentPage === number ? "active" : ""}
                  >
                    {number}
                  </button>
                ))}
              <button
                onClick={() => paginate(currentPage + 1)}
                disabled={publishedblogs.length <= perPage * currentPage}
              >
                Next
              </button>
            </div>
          </div>
          <div className="rightblog_info">
            <div className="topics_sec">
              <h2>Topics</h2>
              <div className="topics_list">
                <Link href={"/topics/htmlcssjs"}>
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <FaHtml5 />
                    </div>
                    <h3>HTML, CSS & JS</h3>
                  </div>
                </Link>
                <Link href={"/topics/nextjs"}>
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <TbBrandNextjs />
                    </div>
                    <h3>Next JS, React JS</h3>
                  </div>
                </Link>
                <Link href={"/topics/database"}>
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <FiDatabase />
                    </div>
                    <h3>Database</h3>
                  </div>
                </Link>
                <Link href={"/topics/deployment"}>
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <AiOutlineDeploymentUnit />
                    </div>
                    <h3>Deployment</h3>
                  </div>
                </Link>
              </div>
            </div>
            <div className="tags_sec mt-3">
              <h2>Tags</h2>
              <div className="tags_list">
                <Link href={"/tag/html"}>#html</Link>
                <Link href={"/tag/css"}>#css</Link>
                <Link href={"/tag/js"}>#js</Link>
                <Link href={"/tag/nextjs"}>#nextjs</Link>
                <Link href={"/tag/reactjs"}>#reactjs</Link>
                <Link href={"/tag/database"}>#database</Link>
              </div>
            </div>
            <div className="letstalk_sec mt-3">
              <h2>Let's Talk</h2>
              <div className="talk_sec">
                <h4>
                  Want to find out how i can solve problems specific to your
                  business? let's talk.
                </h4>
                <div className="social_talk flex flex-center gap-1 mt-2">
                  <div className="st_icon">
                    <FaGithub />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
